CXX = g++
CXXFLAGS = -Wall -g -pedantic
NAME = program
OBJS = lab12.o

all: $(NAME)

# Linking, $@ = left side :  $^ = right side, $< = first dependency
$(NAME): $(OBJS)
	$(CXX) $^ -o $@

# Compiling source files to object files
lab12.o: lab12.cpp Fibonacci.h Stack.h
	$(CXX) $(CXXFLAGS) -c $< -o $@

# The following are commands not files
.PHONY: all clean run

clean:
	rm *.o $(NAME)

run:
	./$(NAME)

